let searchBox = document.querySelector("#search-box");
let images = document.querySelectorAll(".container .image-container .image");
searchBox.oninput = () => {
  images.forEach((hide) => (hide.style.display = "none"));
  let value = searchBox.value;
  images.forEach((filter) => {
    let title = filter.getAttribute("data-title");
    let dataValue = filter.getAttribute("data-value");
    let fullValue = title + " " + dataValue;
    if (value == title) {
      filter.style.display = "block";
    } else if (searchBox.value == "") {
      filter.style.display = "block";
    } else if (searchBox.value == dataValue) {
      filter.style.display = "block";
    }
  });
};

function createRandomImage() {
  //declare an array to store the images
  var randomImage = new Array();
  //insert the URL of images in array
  randomImage[0] = "ducati3.jpeg";
  randomImage[1] = "ducati1.jpeg";
  randomImage[2] = "ducati2.jpeg";
  randomImage[3] = "duke1.jpeg";
  randomImage[4] = "duke2.jpeg";
  randomImage[5] = "duke3.jpeg";
  randomImage[6] = "royal1.jpeg";
  randomImage[7] = "royal2.png";
  randomImage[8] = "royal3.jpeg";
  for (let i = 0; i < 1; i++) {
    //generate a number and provide to the image to generate randomly
    var number = Math.floor(Math.random() * randomImage.length);
    //print the images generated by a random number
    document.getElementsByClassName("image-container")[0].innerHTML =
      '<img src="' + randomImage[number] + '" style="width:600px" />';
  }
  document.getElementById("cont").style.display = "none";
}
